name = "app-loja-adesivos"
compatibility_date = "2025-10-13"

# diretório onde o build do frontend é gerado
pages_build_output_dir = "dist"

# ambiente das Pages com suporte a Functions
[pages]
# aqui é onde ficam suas funções serverless
# (exemplo: /functions/api.js ou /functions/hello.js)
api_directory = "functions"

# variáveis de ambiente opcionais
[vars]
SUPABASE_URL = "https://prayctwxntid6ybvb.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
