name = "app-loja-adesivos"
compatibility_date = "2025-10-13"

[pages]
api_directory = "functions"

[vars]
SUPABASE_URL = "https://prayctwxntid6ybvb.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
